---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: mattandes.p4cli

  post_tasks:
    - name: Get status of P4 binary file
      stat:
        path: /opt/perforce/bin/p4
      register: p4cli_status

    - name: Ensure that binary file exists
      assert:
        that:
          p4cli_status.stat.exists == True
